services:
  otel-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app
      - FLASK_PORT=8000
      - MYSQL_HOST=localhost
      - MYSQL_USER=hackweek
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hackweek
      - REDIS_URL=redis://localhost:6379/0
    links:
      - db-redis
      - db-mysql
    platform: linux/amd64
    ports:
      - "5000:5000"
      - "8080:8080"
    profiles:
      - dev

  db-redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"

  db-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_USER=hackweek"
      - "MYSQL_DATABASE=hackweek"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
