services:
  hackweek:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker-compose.env
    links:
      - db-redis
      - db-mysql
    platform: linux/amd64
    ports:
      - "5000:5000"
      - "8000:8000"

  db-redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"

  db-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_USER=hackweek"
      - "MYSQL_DATABASE=hackweek"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
