apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: fgray-otel-python-app
  labels:
    trigger/app: otel-python-app
    trigger/group: prodeng
    trigger/environment: dev
    trigger/location: us-east-2
    trigger/product: platform
    trigger/project: otel-python-app
    trigger/provider: aws
    app.kubernetes.io/name: python-app
spec:
  template:
    metadata:
      labels:
        trigger/app: otel-python-app
        trigger/group: prodeng
        trigger/environment: dev
        trigger/location: us-east-2
        trigger/product: platform
        trigger/project: otel-python-app
        trigger/provider: aws
        app.kubernetes.io/name: python-app
    spec:
      containers:
        - name: python-app
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=otel-python-app
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-k8s-monitoring-grafana-agent.grafana.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_SERVICE_NAME
              value: otel-python-app
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: env,host,os,serviceinstance
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"

